"""eval1_ik_error (P4): FK(IK(pose)) round-trips under 0.5 mm on the UR20 6R chain.

EVAL_PROVENANCE['eval1_ik_error'] = (P4, "desk: FK(IK(pose)) < 0.5 mm on the
UR20 chain"). This is the desk half of the accuracy story; the rig half (physics
on top of the math) is eval1 in tests/rig, later.

RED until `ur20_kinematics.ik` lands (plan.md phase 2) -- it raises
NotImplementedError today, so the round-trip cannot even be measured yet.
"""
import numpy as np

from palhil.constitution import EVAL_PROVENANCE
from palhil.plant.ur20_kinematics import fk, ik

EVAL = "eval1_ik_error"
TOL_M = 0.5e-3


def test_cites_constitution():
    assert EVAL in EVAL_PROVENANCE, f"{EVAL} not registered in the constitution"


def _reachable_targets(n=120, seed=0):
    """Poses generated by fk() from in-envelope joint vectors are reachable by
    construction; round-tripping them exercises ik then fk over the workspace.
    q5 is kept off zero to stay out of the wrist-singularity guard band."""
    rng = np.random.default_rng(seed)
    targets = []
    for _ in range(n):
        q = rng.uniform(-2.0, 2.0, 6)                       # comfortable, in reach
        q[4] = rng.choice([-1.0, 1.0]) * rng.uniform(0.4, 1.6)  # off wrist singularity
        targets.append(fk(q))
    return targets


def test_ik_fk_roundtrip_position_under_half_mm():
    """eval1: for every reachable target, |FK(IK(T)) - T| position error < 0.5 mm."""
    worst = 0.0
    for T in _reachable_targets():
        q = ik(T)                                           # NotImplementedError -> RED
        worst = max(worst, float(np.linalg.norm(fk(q)[:3, 3] - T[:3, 3])))
    assert worst < TOL_M, f"eval1 FAIL: worst round-trip {worst * 1e3:.3f} mm >= 0.5 mm"
